const { parseAssistantActions, applyAssistantActions, buildCanvasDigest, buildSystemPrompt } = require('./as.cjs')
let fails=0; const check=(n,c,e='')=>{ if(c) console.log('  ✓ '+n); else { fails++; console.log('  ✗ '+n+' '+e) } }
const IDS = ['img-1','gen-1']
const P = (s)=>parseAssistantActions(s, IDS)

console.log('— 能读懂正常回复 —')
let r = P('{"actions":[{"type":"set","nodeId":"gen-1","field":"prompt","value":"a cat"}],"reply":"好"}')
check('一条 set', r.actions.length===1 && r.actions[0].field==='prompt')
r = P('```json\n{"actions":[{"type":"add","kind":"videoGenerator","ref":"v1"}]}\n```')
check('剥掉 ```json 围栏', r.actions.length===1 && r.actions[0].kind==='videoGenerator')
r = P('我帮你加一个节点。\n{"actions":[{"type":"add","kind":"text","ref":"t1"}]}\n就这样。')
check('混在解释文字里也能挑出 JSON', r.actions.length===1)
r = P('{"reply":"里面有 } 和 { 括号","actions":[{"type":"set","nodeId":"img-1","field":"title","value":"a\\"b"}]}')
check('字符串里的花括号/转义引号不干扰', r.actions.length===1 && r.actions[0].value==='a"b', JSON.stringify(r))

console.log('\n— 模型乱说时整条丢掉 —')
check('不是 JSON', P('我不知道').rejected[0]==='noJson')
check('截断的 JSON（花括号没闭合）→ 找不到完整对象', P('{"actions":').rejected[0]==='noJson')
check('花括号闭合但内容非法 → 解析失败', P('{"actions": [oops]}').rejected[0]==='badJson')
check('没有 actions 字段', P('{"reply":"hi"}').rejected[0]==='noActions')
r = P('{"actions":[{"type":"set","nodeId":"不存在","field":"prompt","value":"x"}]}')
check('指向不存在的节点 → 丢', r.actions.length===0 && r.rejected[0].startsWith('set:unknownNode'))
r = P('{"actions":[{"type":"set","nodeId":"gen-1","field":"status","value":"completed"}]}')
check('不许改运行状态 status', r.actions.length===0 && r.rejected[0]==='set:badField:status')
r = P('{"actions":[{"type":"set","nodeId":"gen-1","field":"taskId","value":"x"}]}')
check('不许改 taskId', r.actions.length===0)
r = P('{"actions":[{"type":"set","nodeId":"gen-1","field":"prompt","value":{"a":1}}]}')
check('值是对象 → 丢', r.actions.length===0 && r.rejected[0]==='set:badValue:prompt')
r = P('{"actions":[{"type":"add","kind":"糊弄","ref":"x"}]}')
check('不认识的节点类型 → 丢', r.actions.length===0 && r.rejected[0].startsWith('add:badKind'))
r = P('{"actions":[{"type":"add","kind":"text"}]}')
check('add 没给 ref → 丢', r.actions.length===0 && r.rejected[0]==='add:noRef')
r = P('{"actions":[{"type":"add","kind":"text","ref":"a"},{"type":"add","kind":"text","ref":"a"}]}')
check('ref 撞车 → 第二条丢', r.actions.length===1 && r.rejected[0]==='add:dupRef:a')
r = P('{"actions":[{"type":"connect","from":"gen-1","to":"gen-1"}]}')
check('自己连自己 → 丢', r.actions.length===0 && r.rejected[0]==='connect:selfLoop')
r = P('{"actions":[{"type":"remove","nodeId":"没有这个"}]}')
check('删不存在的节点 → 丢', r.actions.length===0)
r = P('{"actions":[{"type":"run","nodeId":"gen-1"}]}')
check('**助手不许点生成**：run 不是合法动作', r.actions.length===0 && r.rejected[0]==='badType:run')
r = P('{"actions":[{"type":"generate","nodeId":"gen-1"},{"type":"set","nodeId":"gen-1","field":"prompt","value":"ok"}]}')
check('一条坏的不影响后面的好动作', r.actions.length===1 && r.rejected.length===1)

console.log('\n— 同一批里 add 出来的 ref 可以被后面引用 —')
r = P('{"actions":[{"type":"add","kind":"videoGenerator","ref":"v1"},{"type":"set","nodeId":"v1","field":"durationSeconds","value":8},{"type":"connect","from":"img-1","to":"v1"}]}')
check('add → set → connect 三条都留下', r.actions.length===3, JSON.stringify(r.rejected))

console.log('\n— 落到画布上 —')
const ops = (()=>{ let n=0; const o={added:[],patched:[],edges:[],removed:[],origin:{x:100,y:0}}
  o.addNode=(kind,pos,data)=>{ const id='new-'+(++n); o.added.push({id,kind,pos,data}); return id }
  o.updateNodeData=(id,patch)=>o.patched.push({id,patch})
  o.connect=(f,t)=>o.edges.push(f+'->'+t)
  o.removeNodes=(ids)=>o.removed.push(...ids)
  return o })()
const res = applyAssistantActions(P('{"actions":[{"type":"add","kind":"videoGenerator","ref":"v1","fields":{"durationSeconds":8}},{"type":"set","nodeId":"v1","field":"prompt","value":"slow push in"},{"type":"connect","from":"img-1","to":"v1"},{"type":"remove","nodeId":"gen-1"}]}').actions, ops)
check('新建了 1 个', res.added.length===1 && ops.added[0].kind==='videoGenerator')
check('add 时就带上 fields', ops.added[0].data.durationSeconds===8)
check('ref 被换成真 id', ops.patched[0].id==='new-1' && ops.edges[0]==='img-1->new-1')
check('删除照做', ops.removed[0]==='gen-1')
check('统计对得上', res.changed===1 && res.connected===1 && res.removed===1)
const ops2 = {added:[],origin:{x:0,y:0},addNode:(k,p)=>{ops2.added.push(p); return 'n'+ops2.added.length},updateNodeData(){},connect(){},removeNodes(){}}
applyAssistantActions(P('{"actions":[{"type":"add","kind":"text","ref":"a"},{"type":"add","kind":"text","ref":"b"}]}').actions, ops2)
check('多个新节点不叠在一起', ops2.added[0].x !== ops2.added[1].x)

console.log('\n— 讲给模型听的画布摘要 —')
const N=(id,type,data={},sel=false)=>({id,type,position:{x:0,y:0},data,selected:sel})
const big = 'data:image/png;base64,' + 'A'.repeat(50000)
let digest = buildCanvasDigest([N('i1','image',{url:big}), N('g1','imageGenerator',{prompt:'a cat',aspectRatio:'16:9'},true)], [{id:'e',source:'i1',target:'g1'}], ['g1'])
check('**不把 base64 塞进去**', !digest.includes('base64') && digest.length < 600, String(digest.length))
check('图片只说有没有', digest.includes('hasMedia=yes'))
check('带上提示词和画幅', digest.includes('prompt=a cat') && digest.includes('aspectRatio=16:9'))
check('带上连线', digest.includes('i1 -> g1'))
check('带上选中的是谁', digest.includes('SELECTED: g1'))
digest = buildCanvasDigest([N('t','text',{text:'x'.repeat(1000)})], [], [])
check('超长字段截断', digest.length < 400, String(digest.length))
digest = buildCanvasDigest(Array.from({length:120},(_,i)=>N('n'+i,'text',{text:'a'})), [], [])
check('节点太多只讲前 40 个', digest.includes('120 total') && digest.includes('showing 40'))

console.log('\n— 系统提示词 —')
const sys = buildSystemPrompt()
check('明确告诉模型不能点生成', /CANNOT start a generation/.test(sys))
check('系统提示词是英文', !/[一-鿿]/.test(sys))

console.log(fails ? `\n${fails} 条不通过` : '\n全部通过')
process.exit(fails?1:0)
